#+TITLE: Emacs config
#+AUTHOR: Kuhy
#+PROPERTY: header-args+ :comments yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :tangle "~/.emacs.d/init.el"
#+PROPERTY: header-args+ :noweb tangle
#+OPTIONS: prop:t

#+INCLUDE: "../variables.org"

* General
Hide toolbars.
#+BEGIN_SRC elisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(toggle-scroll-bar -1)
(add-to-list 'default-frame-alist
             '(vertical-scroll-bars . nil))
#+END_SRC

Fix problem with downloading =undo-tree=.
=undo-tree= is required by Evil and other packages.
#+BEGIN_SRC elisp
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
#+END_SRC

Load package manager, add the Melpa package registry.
#+BEGIN_SRC elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(setq package-check-signature nil)
(package-initialize)
#+END_SRC

Bootstrap use-package.
#+BEGIN_SRC elisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
#+END_SRC

Hide default welcome screen.
#+BEGIN_SRC elisp
(setq inhibit-startup-screen t)
#+END_SRC

Install package automatically if not already present on your system.
#+BEGIN_SRC elisp
(setq use-package-always-ensure t)
#+END_SRC

Setup font.
#+BEGIN_SRC elisp
(add-to-list 'default-frame-alist
  '(font . "monoid-13"))
#+END_SRC

Display relative line number
#+BEGIN_SRC elisp
(setq-default display-line-numbers-type 'relative)
(global-display-line-numbers-mode t)
#+END_SRC

* Org
Alow to run dot files from =org-mode=.
#+BEGIN_SRC elisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((dot . t))) ; this line activates dot
#+END_SRC

Highlight LaTeX commands inside Org Mode.
#+BEGIN_SRC elisp
(setq org-highlight-latex-and-related '(latex script entities))
#+END_SRC

Change org-mode exporting process to pdf.
Needed for bibtex support.
#+BEGIN_SRC elisp
(setq org-latex-pdf-process
      '("latexmk -pdflatex='pdflatex -interaction nonstopmode' -pdf -bibtex -f %f"))
#+END_SRC

Run org-mode code snippets without confirmation.
#+BEGIN_SRC elisp
(setq org-confirm-babel-evaluate nil)
#+END_SRC

Set org-mode keybindings:
#+BEGIN_SRC elisp
(global-set-key (kbd "C-c a") 'org-agenda)
#+END_SRC

* Packages
Use dashboard as a welcome screen.
#+BEGIN_SRC elisp
(use-package dashboard
  :config
  (setq dashboard-startup-banner 3)
  (dashboard-setup-startup-hook)
  (setq initial-buffer-choice (lambda () (switch-to-buffer "*dashboard*"))))
#+END_SRC

Use editorconfig.
#+BEGIN_SRC elisp
(use-package editorconfig
  :config
  (editorconfig-mode 1))
#+END_SRC

Alows managing window configurations similary to tiling WMs.
#+BEGIN_SRC elisp
(use-package eyebrowse
  :config
  (eyebrowse-mode)
  (eyebrowse-setup-opinionated-keys))
#+END_SRC

Support for vim keybindings.
#+BEGIN_SRC elisp
(use-package evil
  :defer .1
  :config
  (evil-mode))
#+END_SRC

Tool for minibuffer completion.
#+BEGIN_SRC elisp
(use-package ivy
  :defer .1
  :custom
  (ivy-use-virtual-buffers t)
  (ivy-count-format "%d/%d ")
  :config
  (ivy-mode))
#+END_SRC

=Counsel=, a collection of Ivy-enhanced versions of common Emacs commands.
#+BEGIN_SRC elisp
(use-package counsel
  :after ivy
  :config (counsel-mode))
#+END_SRC

More friendly interface for ivy.
#+BEGIN_SRC elisp
(use-package ivy-rich
  :after ivy
  :custom
  (ivy-rich-path-style 'abbrev)
  :config
  (ivy-rich-mode 1))
#+END_SRC

Package that displays available keybindings in popup.
#+BEGIN_SRC elisp
(use-package which-key
  :defer 0.2
  :diminish
  :config (which-key-mode))
#+END_SRC

=Git= interface.
#+BEGIN_SRC elisp
(use-package magit)
#+END_SRC

=Magit= support for =evil-mode=.
#+BEGIN_SRC elisp
(use-package evil-magit
  :after (evil magit))
#+END_SRC

Package for highlighting uncommitted changes.
#+BEGIN_SRC elisp
(use-package diff-hl
  :demand t
  :hook (magit-post-refresh diff-hl-magit-post-refresh)
  :config (global-diff-hl-mode))
#+END_SRC

#+BEGIN_SRC elisp
(use-package tex
  :defer t
  :ensure auctex
  :config
  (TeX-source-correlate-mode)
  (add-to-list 'TeX-view-program-selection
               '(output-pdf "Zathura")))
#+END_SRC

Markdown support:
#+BEGIN_SRC elisp
(use-package markdown-mode
  :ensure t
  :commands (markdown-mode gfm-mode)
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :init (setq markdown-command "multimarkdown"))
#+END_SRC

Project Interaction Library
#+BEGIN_SRC elisp
(use-package projectile
  :ensure t
  :config
  (define-key projectile-mode-map (kbd "M-p") 'projectile-command-map)
  (projectile-mode +1))
#+END_SRC

On the fly syntax checking for GNU Emacs
#+BEGIN_SRC elisp
(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))
#+END_SRC

Text completion framework
#+BEGIN_SRC elisp
(use-package company)
#+END_SRC

Emacs client/library for the Language Server Protocol
#+BEGIN_SRC elisp
(use-package lsp-mode
  :hook (python-mode . lsp)
  :commands lsp)

(use-package lsp-ui :commands lsp-ui-mode)
(use-package company-lsp :commands company-lsp)
#+END_SRC

Debug adapter protocol
#+BEGIN_SRC elisp
(use-package dap-mode
  :after lsp-mode
  :config
  (dap-mode t)
  (dap-ui-mode t))
#+END_SRC

LSP for Java
#+BEGIN_SRC elisp
(use-package hydra)
(use-package lsp-java :after lsp
  :config (add-hook 'java-mode-hook 'lsp)
          (require 'dap-java))
#+END_SRC

A template system
#+BEGIN_SRC elisp
(use-package yasnippet-snippets)
(use-package yasnippet
  :config (yas-global-mode 1))
#+END_SRC

* Theme
Set base 16 theme:
#+BEGIN_SRC elisp
(use-package base16-theme
  :init
  (setq base16-default-dark-colors
  '(:base00 "<<base00>>"
    :base01 "<<base01>>"
    :base02 "<<base02>>"
    :base03 "<<base03>>"
    :base04 "<<base04>>"
    :base05 "<<base05>>"
    :base06 "<<base06>>"
    :base07 "<<base07>>"
    :base08 "<<base08>>"
    :base09 "<<base09>>"
    :base0A "<<base0A>>"
    :base0B "<<base0B>>"
    :base0C "<<base0C>>"
    :base0D "<<base0D>>"
    :base0E "<<base0E>>"
    :base0F "<<base0F>>"))
  :config
  (load-theme 'base16-default-dark t))
#+END_SRC

Set the cursor color based on the evil state
#+BEGIN_SRC elisp
(defvar my/base16-colors base16-default-dark-colors)
(setq evil-emacs-state-cursor   `(,(plist-get my/base16-colors :base0D) box)
      evil-insert-state-cursor  `(,(plist-get my/base16-colors :base0D) bar)
      evil-motion-state-cursor  `(,(plist-get my/base16-colors :base0E) box)
      evil-normal-state-cursor  `(,(plist-get my/base16-colors :base0B) box)
      evil-replace-state-cursor `(,(plist-get my/base16-colors :base08) bar)
      evil-visual-state-cursor  `(,(plist-get my/base16-colors :base09) box))
#+END_SRC
