#+TITLE: Firefox
#+AUTHOR: Kuhy
#+OPTIONS: prop:t
#+INCLUDE: "../variables.org"
/Standalone web browser from Mozilla/
* Profiles
  :PROPERTIES:
  :header-args: :tangle ~/.mozilla/firefox/profiles.ini :comments both :mkdirp yes :noweb tangle
  :END:
  Use only one profile called "default".
  #+BEGIN_SRC conf
    [General]
    StartWithLastProfile=1

    [Profile0]
    Name=default
    IsRelative=1
    Path=default
    Default=1
  #+END_SRC
* General
  :PROPERTIES:
  :header-args: :tangle ~/.mozilla/firefox/default/user-overrides.js :comments both :mkdirp yes :noweb tangle
  :END:
  Make Tridactyl work on addons.mozilla.org and some other Mozilla domains
  #+BEGIN_SRC js
    user_pref("privacy.resistFingerprinting.block_mozAddonManager", true);
    user_pref("extensions.webextensions.restrictedDomains", "");
  #+END_SRC

  Allow stylesheets modifications (userChrome.css, userContent.css)
  #+BEGIN_SRC js
    user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
  #+END_SRC

  Printing with no headers and footers:
  #+BEGIN_SRC js
    user_pref("print.print_footerleft", "");
    user_pref("print.print_footerright", "");
    user_pref("print.print_headerleft", "");
    user_pref("print.print_headerright", "");
  #+END_SRC

  Turn on caret browsing mode.
  #+BEGIN_SRC js
    user_pref("accessibility.browsewithcaret", true);
  #+END_SRC

  Disable extension recommendations.
  #+BEGIN_SRC js
    user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);
  #+END_SRC

  HTTP referrer is a violation of privacy
  (the HTTP header field that identifies the webpage you just
  came from which was linked to the webpage you are going to)
  #+BEGIN_SRC js
    user_pref("Network.http.sendRefererHeader", 0);
  #+END_SRC

  Disable Pocket:
  #+BEGIN_SRC js
    user_pref("extensions.pocket.enabled", false);
  #+END_SRC

  Enable /compact mode/ (*note*: Choose =Compact (not supported)= from =Customize Toolbar=):
  #+BEGIN_SRC js
    user_pref("browser.compactmode.show", true);
    user_pref("browser.uidensity", 1);
  #+END_SRC

  Disable /Firefox View/:
  #+BEGIN_SRC js
    user_pref("browser.tabs.firefox-view", false);
  #+END_SRC

  Do not show bookmarks toolbar:
  #+BEGIN_SRC js
    user_pref("browser.toolbars.bookmarks.visibility", "never");
  #+END_SRC

  Control /newtab/ using Tridactyl:
  #+BEGIN_SRC js
    user_pref("browser.newtab.extensionControlled", true);
  #+END_SRC

  Set homepage:
  #+BEGIN_SRC js
    user_pref("browser.startup.firstrunSkipsHomepage", false);
    user_pref("browser.startup.page", 1);
    user_pref("browser.startup.homepage", "https://archlinux.org/");
  #+END_SRC

  Do not remember passwords:
  #+BEGIN_SRC js
    user_pref("signon.rememberSignons", false);
  #+END_SRC
* Tridactyl
** General
   :PROPERTIES:
   :header-args: :tangle ~/.config/tridactyl/tridactylrc :comments both :mkdirp yes :noweb tangle
   :END:
   Use old reddit.
   #+BEGIN_SRC conf
     autocmd DocStart ^http(s?)://www.reddit.com js tri.excmds.urlmodify("-t", "www", "old")
   #+END_SRC

   Website shortcuts:
   #+BEGIN_SRC conf
     set searchurls.g https://google.com/search?q=%s
     set searchurls.y https://duckduckgo.com/?ia=videos&iax=videos&q=%s
     set searchurls.d https://duckduckgo.com/?q=%s
     set searchurls.s https://stackoverflow.com/search?q=%s
     set searchurls.r https://old.reddit.com/r/%s
     set searchurls.w https://en.wikipedia.org/w/index.php?search=%s

     quickmark m https://mail.google.com
     quickmark f https://facebook.com
     quickmark t https://is.muni.cz/auth/rozvrh
     quickmark i https://is.muni.cz/auth/student
     quickmark c https://calendar.google.com
     quickmark g https://github.com/kuhy
     quickmark s https://www.southparkstudios.com/random-episode
   #+END_SRC

   Load theme.
   #+BEGIN_SRC conf
     colorscheme theme
   #+END_SRC

   Use browser search engine
   #+BEGIN_SRC conf
     set searchengine ""
   #+END_SRC

   Set blank page as a new tab:
   #+BEGIN_SRC conf
     set newtab about:blank
   #+END_SRC

   Disable numeral prefixing (via hack):
   #+BEGIN_SRC conf
     keymap 0 @
     keymap 1 @
     keymap 2 @
     keymap 3 @
     keymap 4 @
     keymap 5 @
     keymap 6 @
     keymap 7 @
     keymap 8 @
     keymap 9 @
   #+END_SRC
** Theme
   :PROPERTIES:
   :header-args: :tangle ~/.config/tridactyl/themes/theme.css :comments both :mkdirp yes :noweb tangle
   :END:
   #+BEGIN_SRC css
     :root {    /* Default-dark by Chris Kempson (http://chriskempson.com) */
         --base00: #<<base00>>;
         --base01: #<<base01>>;
         --base02: #<<base02>>;
         --base03: #<<base03>>;
         --base04: #<<base04>>;
         --base05: #<<base05>>;
         --base06: #<<base06>>;
         --base07: #<<base07>>;
         --base08: #<<base08>>;
         --base09: #<<base09>>;
         --base0A: #<<base0A>>;
         --base0B: #<<base0B>>;
         --base0C: #<<base0C>>;
         --base0D: #<<base0D>>;
         --base0E: #<<base0E>>;
         --base0F: #<<base0F>>;

         --tridactyl-fg: var(--base05);
         --tridactyl-bg: var(--base00);
         --tridactyl-url-fg: var(--base0D);
         --tridactyl-url-bg: var(--base00);
         --tridactyl-highlight-box-bg: var(--base04);
         --tridactyl-highlight-box-fg: var(--base00);

         /* Hint character tags */
         --tridactyl-hintspan-fg: var(--base00) !important;
         --tridactyl-hintspan-bg: var(--base0A) !important;

         /* Element Highlights */
         --tridactyl-hint-active-fg: none;
         --tridactyl-hint-active-bg: none;
         --tridactyl-hint-active-outline: none;
         --tridactyl-hint-bg: none;
         --tridactyl-hint-outline: none;
     }

     #command-line-holder {    order: 1;
         border: 2px solid var(--base04);
         color: var(--tridactyl-bg);
     }

     #tridactyl-input {    padding: 1rem;
         color: var(--tridactyl-fg);
         width: 90%;
         font-size: 1.2rem;
         line-height: 1.2;
         background: var(--tridactyl-bg);
         padding-left: unset;
         padding: 1rem;
     }

     #completions table {    font-size: 0.8rem;
         font-weight: 200;
         border-spacing: 0;
         table-layout: fixed;
         padding: 1rem;
         padding-top: unset;
         padding-bottom: 1rem;
     }

     #completions > div {    max-height: calc(20 * var(--option-height));
         min-height: calc(10 * var(--option-height));
     }

     /* COMPLETIONS */

     #completions {    --option-height: 1.4em;
         color: var(--tridactyl-fg);
         background: var(--tridactyl-bg);
         display: inline-block;
         font-size: unset;
         font-weight: 200;
         overflow: hidden;
         width: 100%;
         border-top: unset;
         order: 2;
     }

     /* Olie doesn't know how CSS inheritance works */
     #completions .HistoryCompletionSource {    max-height: unset;
         min-height: unset;
     }

     #completions .HistoryCompletionSource table {    width: 100%;
         font-size: 9pt;
         border-spacing: 0;
         table-layout: fixed;
     }

     /* redundancy 2: redundancy 2: more redundancy */
     #completions .BmarkCompletionSource {    max-height: unset;
         min-height: unset;
     }

     #completions table tr td.prefix,#completions table tr td.privatewindow,#completions table tr td.container,#completions table tr td.icon {    display: none;
     }

     #completions .BufferCompletionSource table {    width: unset;
         font-size: unset;
         border-spacing: unset;
         table-layout: unset;
     }

     #completions table tr .title {    width: 50%;
     }

     #completions table tr {    white-space: nowrap;
         overflow: hidden;
         text-overflow: ellipsis;
     }

     #completions .sectionHeader {    background: unset;
         font-weight: 200;
         border-bottom: unset;
         padding: 1rem !important;
         padding-left: unset;
         padding-bottom: unset;
     }

     #cmdline_iframe {    position: fixed !important;
         bottom: unset;
         top: 25% !important;
         left: 10% !important;
         z-index: 2147483647 !important;
         width: 80% !important;
         box-shadow: rgba(0, 0, 0, 0.5) 0px 0px 20px !important;
     }

     .TridactylStatusIndicator {    position: fixed !important;
         bottom: 0 !important;
         background: var(--tridactyl-bg) !important;
         border: unset !important;
         border: 1px var(--base0B) solid !important;
         font-size: 12pt !important;
         /*font-weight: 200 !important;*/
         padding: 0.8ex !important;
     }

     #completions .focused {    background: var(--tridactyl-highlight-box-bg);
         color: var(--base00);
     }

     #completions .focused .url {    background: var(--tridactyl-highlight-box-bg);
         color: var(--base00);
     }
   #+END_SRC
* Styles
** User interface
   :PROPERTIES:
   :header-args: :tangle ~/.mozilla/firefox/default/chrome/userChrome.css :comments both :mkdirp yes :noweb tangle
   :END:
   Declare color variables:
   #+BEGIN_SRC css
     :root {
         --bar-color: #<<base01>>;
         --bar-text-color: #<<base06>>;
         --tab-color: #<<base02>>;
         --tab-text-color: #<<base05>>;
         --tab-selected-color: #<<base0D>>;
         --tab-selected-text-color: #<<base00>>;
         --warning-color: #<<base0A>>;
     }
   #+END_SRC

   Hide useless stuff:
   #+BEGIN_SRC css
     #webrtcIndicator,
     .tab-close-button,
     .tab-icon-image,
     #PanelUI-menu-button,
     #downloads-button,
     #home-button,
     #back-button,
     #forward-button,
     #sidebar-button,
     #alltabs-button,
     #tabs-newtab-button,
     toolbarspring,
     #sidebar-header
     {
       display: none !important
     }
   #+END_SRC

   Show tab numbers:
   #+BEGIN_SRC css
     tabs {
       counter-reset: tab-counter;
     }

     .tab-label::before {
       counter-increment: tab-counter;
       content: counter(tab-counter) ": ";
     }
   #+END_SRC

   Reduce tab title font:
   #+BEGIN_SRC css
     .tabbrowser-tab[fadein]:not([pinned]) {
         font-size: 0.9em !important;
     }
   #+END_SRC

   URL bar font size is reduced:
   #+BEGIN_SRC css
     #urlbar {
       font-size: 0.8em !important;
     }
   #+END_SRC

   Change colors and tabs appearance:
   #+BEGIN_SRC css
     .tab-line{
       visibility: collapse !important;
     }

     .tab-background {
       border: none !important;
       background-attachment: none!important;
       background-color: var(--tab-selected-color) !important;
       background-image: none!important;
     }

     .tabbrowser-tab:not([selected]) .tab-background {
       border: none !important;
       background-color: var(--tab-color) !important;
     }

     .tabbrowser-tab:not([selected]) .tab-label {
       color : var(--tab-text-color) !important;
     }

     .tabbrowser-tab[selected] .tab-label {
       color : var(--bar-color) !important;
     }

     .tab-context-line {
       background-color: var(--tab-text-color) !important;
     }

     #urlbar-background{
       background-color: var(--tab-text-color) !important;
     }

     #nav-bar,#urlbar-container,#urlbar,#PanelUI-menu-button{
       color : var(--tab-color) !important;
       background-color: var(--bar-color) !important;
     }

     #navigator-toolbox toolbarbutton {
       fill: var(--bar-text-color) !important;
     }

     .titlebar-color{
       color : var(--tab-text-color);
       background-color: var(--bar-color) !important;
     }

     .tab-throbber[busy] {
        animation: unset !important;
        background-image: unset !important;
        background-color: var(--warning-color) !important;
     }
   #+END_SRC

   Reduce the tabs height more:
   #+BEGIN_SRC css
     :root #tabbrowser-tabs {
      --tab-min-height: 22px !important;
     }
   #+END_SRC

   Make the tabs hidden when there is only one tab open:
   #+BEGIN_SRC css
     :root[sizemode="normal"] #nav-bar{ --uc-window-drag-space-width: 20px }
     #titlebar{ -moz-appearance: none !important; }
     #TabsToolbar{ min-height: 0px !important }
     #tabbrowser-tabs, #tabbrowser-tabs > .tabbrowser-arrowscrollbox, #tabbrowser-arrowscrollbox{ min-height: 0 !important; }
     :root:not([customizing]) #tabbrowser-tabs .tabs-newtab-button,
     :root:not([customizing]) #tabs-newtab-button,
     :root:not([customizing]) #TabsToolbar-customization-target > .toolbarbutton-1,
     :root:not([customizing]) #TabsToolbar .titlebar-button{
       -moz-appearance: none !important;
       height: 0px;
       padding-top: 0px !important;
       padding-bottom: 0px !important;
       -moz-box-align: stretch;
       margin: 0 !important;
     }
     #tabbrowser-tabs .tabbrowser-tab{ height: var(--tab-min-height) }
     #tabbrowser-tabs .tabbrowser-tab[first-visible-tab="true"][last-visible-tab="true"]{
       visibility: collapse !important;
     }
     #tabs-newtab-button:hover,
     #tabbrowser-tabs .tabs-newtab-button:hover{ background-color: var(--toolbarbutton-hover-background) }

     #tabs-newtab-button > .toolbarbutton-icon,
     #tabbrowser-tabs .tabs-newtab-button > .toolbarbutton-icon{
       padding: 0 !important;
       transform: scale(0.6);
       background-color: transparent !important;
     }
     @media (-moz-os-version: windows-win10){
       :root[sizemode="maximized"] #navigator-toolbox{ padding-top:7px !important; }
     }
     :root[tabsintitlebar] #toolbar-menubar[autohide="true"][inactive]{
       transition: height 0ms steps(1) 80ms;
     }
     #nav-bar{
       border-inline: var(--uc-window-drag-space-width) solid var(--toolbar-bgcolor);
     }
   #+END_SRC
** Web pages
   :PROPERTIES:
   :header-args: :tangle ~/.mozilla/firefox/default/chrome/userContent.css :comments both :mkdirp yes :noweb tangle
   :END:
   Change color of scroll bar:
   #+BEGIN_SRC css
     html,body{
         scrollbar-color: #<<base03>> #<<base01>> !important;
     }
   #+END_SRC
